package vn.com.fwd.sms.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-10-07T11:37:56.286+07:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://service.sms.fwd.com/", name = "NotificationService")
@XmlSeeAlso({ObjectFactory.class})
public interface NotificationService {

    @WebMethod(operationName = "CreateSmsRequest")
    @RequestWrapper(localName = "CreateSmsRequest", targetNamespace = "http://service.sms.fwd.com/", className = "com.fwd.sms.service.CreateSmsRequest")
    @ResponseWrapper(localName = "CreateSmsRequestResponse", targetNamespace = "http://service.sms.fwd.com/", className = "com.fwd.sms.service.CreateSmsRequestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean createSmsRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );
}
