package vn.com.fwd.sms.webservice;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-10-07T11:37:56.317+07:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "NotificationServiceService", 
                  targetNamespace = "http://service.sms.fwd.com/") 
public class NotificationServiceService extends Service {

    public final static QName SERVICE = new QName("http://service.sms.fwd.com/", "NotificationServiceService");
    public final static QName NotificationServicePort = new QName("http://service.sms.fwd.com/", "NotificationServicePort");
    

    public NotificationServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NotificationService
     */
    @WebEndpoint(name = "NotificationServicePort")
    public NotificationService getNotificationServicePort() {
        return super.getPort(NotificationServicePort, NotificationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationService
     */
    @WebEndpoint(name = "NotificationServicePort")
    public NotificationService getNotificationServicePort(WebServiceFeature... features) {
        return super.getPort(NotificationServicePort, NotificationService.class, features);
    }

}
